name: 'Webhook notify action'
description: 'Send a payload to a webhook'
author: 'Smartly.io'
inputs:
  webhook_url:
    description: 'The HTTP URI of the webhook endpoint to invoke'
    required: true
  webhook_secret:
    description: 'The secret with which to generate the signature hash'
    required: true
  webhook_auth:
    description: 'Credentials to be used for Bearer token authentication'
    required: true
  data:
    description: 'Extra webhook payload, included under a "data" key'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
