name: Check Labels

on:
  pull_request:
    branches:
    - master
    types:
    - opened
    - labeled
    - unlabeled
    - synchronize

jobs:
  check_labels:
    runs-on: ubuntu-20.04
    steps:
    - uses: smartlyio/check-versioning-action@v5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

