name: Build and release the action

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "Test"
      run: |
        npm run test
    - name: "build"
      run: |
        npm run build
        npm run package

  test:
    runs-on: ubuntu-22.04
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
        - 8080:80
    steps:
    - uses: actions/checkout@v4
    - name: Set Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - name: "Build action for test"
      run: |
        npm install
        npm run build
        npm run package
        git clean -fXd
    - name: Test executing the action
      uses: ./
      with:
        webhook_url: http://localhost:8080/post
        webhook_secret: supersecret
        webhook_auth: othersecret
        data: '{"my-key": "my-value"}'

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
