###############################################################################
# IMPORTANT NOTE/WARNING!                                                     #
# This file is automagically updated from the smartlyio/smartly-gha repo      #
# Do not make changes to this file, your changes will be overwritten          #
# Talk to Vulcan/DevOps if you want changes or to make your own modifications #
###############################################################################

name: Self Updater

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows.yml'
      - '.github/workflows/*.yml'
      - '.github/templates/*.yml.erb'
      - '.github/args.yml'
  schedule:
    - cron:  '1 6-22 * * 1-5'

jobs:
  update_gha:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false
          fetch-depth: 0
      - name: Use templater to pull template ref
        id: fetch_ref
        run: |
              # Get the template_ref from the args file if it exists, any errors default to master
              VARS_FILE=".github/args.yml"
              # Check that the branch spec is correct as per spec
              # Using example found here: https://stackoverflow.com/questions/12093748/how-do-i-check-for-valid-git-branch-names
              TEMPLATE_PULL_REF=$(grep "template_ref: " "$VARS_FILE" | sed -e "s/template_ref: //" | grep -P '^(?!.*/\.)(?!.*\.\.)(?!/)(?!.*//)(?!.*@\\{)(?!@$)(?!.*\\)[^\000-\037\177 ~^:?*[]?/?[^\000-\037\177 ~^:?*[]+(?<!\.lock)(?<!/)(?<!\.)$' || echo "master")
              # Output variable so we can use them again
              echo ::set-env name=VARS_FILE::"$VARS_FILE"
              echo ::set-env name=TEMPLATE_PULL_REF::"$TEMPLATE_PULL_REF"
              echo ::set-output name=VARS_FILE::"$VARS_FILE"
              echo ::set-output name=TEMPLATE_PULL_REF::"$TEMPLATE_PULL_REF"
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.SMARTLY_GHA_TEMPLATES }}
          ref: ${{ steps.fetch_ref.outputs.TEMPLATE_PULL_REF }}
          ssh-key: ${{ secrets.GIT_DEPLOY_KEY }}
          path: .github/templates/smartlyio
      - name: Use Publish to set up SSH key
        uses: smartlyio/setup-git-action@v1
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
      - name: Setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Install kojo
        run: |
              gem install kojo
              echo ::set-env name=KOJO_INTERACTIVE::"no"
              echo ::set-env name=KOJO_BINARY::"$(which kojo)"
      - name: Run templater
        env:
          UBUNTU_VERSION: ubuntu-18.04
        run: |
              mkdir -p .github/workflows
              rm .github/workflows/*.generated.yml
              if [ -f "$VARS_FILE" ]; then
                find .github/templates/*.yml.erb | xargs -n 1 basename -s .yml.erb | xargs -n 1 -I [] bash -c "$KOJO_BINARY file .github/templates/[].yml.erb --args $VARS_FILE --save .github/workflows/[].generated.yml ubuntu_version=$UBUNTU_VERSION"
              else 
                find .github/templates/*.yml.erb | xargs -n 1 basename -s .yml.erb | xargs -n 1 -I [] bash -c "$KOJO_BINARY file .github/templates/[].yml.erb --save .github/workflows/[].generated.yml ubuntu_version=$UBUNTU_VERSION"
              fi
              # Remove templates so we don't accidentally commit them
              rm -rf .github/templates/smartlyio
      - name: Push changes if required
        run: |
          git status
          git_changes=$(git status --porcelain | grep .github || true)
          if [[ $git_changes ]]; then
              echo "Changes to workflows found!"
              git add .github/workflows/*
              git commit -m "Adding workflow changes at $(date)"
              git push
          else
              echo "No Changes Found."
              exit 0
          fi